services:
  scheduler:
    container_name: room_automation_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5500:5500"
